Development
serdg0/tic-tac-toe_rspec pull request #1
Opened 2019-08-09 16:14 UTC by serdg0

2019-08-09 22:17 UTC, mosaaleb requested changes
## Well done @AlejoCode, @serdg0 :clap:

### All test cases are green :rocket:, however there is some requirements needs to be handled before moving on.

- [ ] There is alot of errors related to styling guidelines

![Screenshot from 2019-08-10 00-10-45](https://user-images.githubusercontent.com/4246637/62811786-53fe9500-bb03-11e9-9ee4-c1400080ab6d.png)

Please, take a look at [guidelines](https://github.com/rubocop-hq/ruby-style-guide) and  let's fix these errors. You also need to use stickler with rubocop specified inside `.stickler.yml` [stickler](https://github.com/microverseinc/linters-config/tree/master/ruby)

**TIP** You can install rubocop extension available on every text editor to catch these erros while you wrote them, before even pushing.

- [x] Let vs static variables. Please see my [comment](https://github.com/serdg0/tic-tac-toe_rspec/pull/1#discussion_r312659650).

**Friendly reminder:** You should use Git Flow in this project. However, changing it now would take too much time. Please make sure you use Github/Git Flow in the next project. You will find instructions in the Path-wright lesson description.

Please fix these minor requirements and submit a new code review.

### Happy Coding :computer:

2019-08-09 22:17 UTC, mosaaleb commented on spec/game_spec.rb
> +require './lib/tic-tac-toe'
- [ ] All the public methods of the classes implemented in project OOP are tested
There are some method in Game class are not tested yet `#turn`, `#turn_count`, `#draw`, `#get_input`, `#not_repeated` .... 
Let's add them.

2019-08-09 22:17 UTC, mosaaleb commented on spec/game_spec.rb
> +RSpec.describe Game do
- [x] To define a variable, you need to use `let`
Why it's different from creating instance variables? `let` uses lazy evaluation means that if the variable won't be created unless it is invoked
So `let(:game) { Game.new }` won't be created unless you references `game` inside an example.

Here are some references to read more about:
- [let vs instance variable](https://mixandgo.com/learn/let-vs-instance-variables-in-rspec)
- [when to use let vs instance](https://stackoverflow.com/questions/14116613/when-is-using-instance-variables-more-advantageous-than-using-let)

2019-08-09 22:17 UTC, mosaaleb commented on spec/board_spec.rb
> +            board.return_board_input(3,player)
- **`[OPTIONAL]`** There is a convention in rspec that if you are testing specific functionality don't use another methods in that test. For example here we are testing `check_winner` and we are using another method `return_board_input`, now what if this other method is buggy and the test fails? You will waste alot of time trying to fix `check_winner`, but the other method is the one you need to fix.

To fix this we can manually stub the board cells with our desired values.

2019-08-10 02:22 UTC, bellom commented
## Currently Reviewing this PR

2019-08-10 02:35 UTC, bellom requested changes
Hi @serdg0 @AlejoCode, 
Well done guys, according to the previous review, you still need to work on those changes mentioned by the reviewer, you only two test case inside the `game_spec`.
And am not seeing linter check on this project, but previous reviewer talk about it, i hope am not missing something....kindly add the linter and fix all errors if need too, checkout this [link](https://github.com/microverseinc/linters-config#troubleshooting) for help.
kindly re-submit for review after making those changes....

2019-08-13 05:10 UTC, bellom commented
Currently reviewing this PR

2019-08-13 05:30 UTC, bellom approved these changes
Hi Team,
Well done guys.
Kindly know that it's part of the project requirement to add linter and be sure to use `Git Flow` when necessary.
**Go head merge :+1:** 
Goodluck in your next project.

2019-08-13 13:46 UTC, merged